# Generated by Django 4.1.5 on 2023-01-27 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='anser',
            new_name='answer',
        ),
    ]
